# fly.toml app configuration file generated for sefaria-discord-bot
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "sefaria-discord-bot"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  builder = "dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[processes]
  app = "python main.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "echo 'Starting Sefaria Discord Bot with comprehensive Jewish learning features'"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"
